language: node_js
node_js:
  - "8.2.1"

script:
  - npm run build

after_success:
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && npm run deploy

notifications:
  - email:
    on_failure: change
    on_success: change
